### ISSUE TITLE
Compilation error w. Coq 8.6

### ISSUE THREAD

**Issue by kushti** [adampetcher/fcf#6]
COQC Rat.v
File "./Rat.v", line 188, characters 2-26:
Error: Found no subterm matching "(x * n1)%nat" in the current goal.

**Comment by adampetcher** [comment]
The code hasn't been updated to work with 8.6 yet. We can leave this ticket open to track the request to make it work with 8.6. How urgent is your need to have FCF working with 8.6? Can you use 8.5 in the meantime?

**Comment by kushti** [comment]
No rush, Adam, I made the ticket just in order to inform you.

**Comment by adampetcher** [comment]
I just pulled in a commit from Andres that makes (most) everything work in 8.6, so I'm considering this issue closed. Please open a new request for any additional files that don't currently build but are needed.
